version: '2.0'

services:
  postgresdb:
    restart: always
    image: postgres
    env_file:
      - example/docker-files/environ
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - shopnet

  redishost:
    image: redis
    volumes:
      - 'redisdata:/data'
    networks:
      - shopnet

  elasticsearch:
    image: elasticsearch:1.7.5
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - shopnet

  django:
    restart: always
    build:
      context: .
      dockerfile: example/docker-files/Dockerfile
    image: demoshop
    environment:
      - DJANGO_SHOP_TUTORIAL
      - POSTGRES_DB=myshop_$DJANGO_SHOP_TUTORIAL
      - DJANGO_EMAIL_HOST
      - DJANGO_EMAIL_PORT
      - DJANGO_EMAIL_USER
      - DJANGO_EMAIL_PASSWORD
      - DJANGO_EMAIL_USE_TLS
      - DJANGO_EMAIL_FROM
      - DJANGO_EMAIL_REPLY_TO
    env_file:
      - example/docker-files/environ
    volumes:
      - shopmedia:/web/workdir
    depends_on:
      - postgresdb
      - redishost
      - elasticsearch
    networks:
      - shopnet
    command: uwsgi --ini uwsgi.ini
    ports:
      - 9009:9009

  worker:
    restart: always
    image: demoshop
    environment:
      - DJANGO_SHOP_TUTORIAL
      - POSTGRES_DB=myshop_$DJANGO_SHOP_TUTORIAL
      - DJANGO_SETTINGS_MODULE=myshop.settings
    env_file:
      - example/docker-files/environ
    command: su django -c /web/worker.py
    depends_on:
      - postgresdb
      - redishost
    networks:
      - shopnet

networks:
  shopnet:

volumes:
  pgdata:
  redisdata:
  shopmedia:
  esdata:
